import type { Anchor, DrawingType, DrawingStyle } from '@graph/shared-types';

/**
 * BaseTool — abstract interface for all drawing tools.
 * Each tool implements its own creation gesture (number of clicks, drag behavior).
 */

export interface ToolCreateResult {
    type: DrawingType;
    anchors: Anchor[];
    style: Partial<DrawingStyle>;
}

export type ToolEventType = 'anchor_placed' | 'preview_update' | 'complete' | 'cancel';

export interface ToolEvent {
    type: ToolEventType;
    /** Partial result — complete anchors so far */
    anchors: Anchor[];
    /** Preview anchor (mouse position during mousemove) */
    previewAnchor?: Anchor;
    /** Optional style overrides generated by the tool */
    style?: Partial<DrawingStyle>;
}

export type ToolEventCallback = (event: ToolEvent) => void;

export abstract class BaseTool {
    protected anchors: Anchor[] = [];
    protected callback: ToolEventCallback;
    protected magnetEnabled: boolean = false;

    constructor(callback: ToolEventCallback) {
        this.callback = callback;
    }

    /** How many anchor clicks are needed to complete this tool */
    abstract get requiredAnchors(): number;

    /** The drawing type this tool produces */
    abstract get drawingType(): DrawingType;

    /** Default style for this tool */
    abstract get defaultStyle(): Partial<DrawingStyle>;

    /** Handle a click/tap at the given data-space position */
    onAnchorPlaced(anchor: Anchor): void {
        this.anchors.push(anchor);
        this.callback({ type: 'anchor_placed', anchors: [...this.anchors] });

        if (this.anchors.length >= this.requiredAnchors) {
            this.callback({
                type: 'complete',
                anchors: [...this.anchors],
            });
            this.reset();
        }
    }

    /** Handle mouse/touch move for preview (rubber-band effect) */
    onPreviewMove(anchor: Anchor): void {
        this.callback({
            type: 'preview_update',
            anchors: [...this.anchors],
            previewAnchor: anchor,
        });
    }

    /** Cancel the current tool operation */
    cancel(): void {
        this.callback({ type: 'cancel', anchors: [] });
        this.reset();
    }

    /** Enable/disable magnet snap */
    setMagnet(enabled: boolean): void {
        this.magnetEnabled = enabled;
    }

    protected reset(): void {
        this.anchors = [];
    }
}
